### ISSUE TITLE
有可能将simple上的博客内容同步提交到 GitCafe Page吗？

### ISSUE THREAD

**Issue by vxxholic** [isnowfy/simple#14]
我这边的ISP可能把github封了，基本上就只有我自己能看到自己的博客，于是就搜到了这篇文章（http://www.wtoutiao.com/a/842872.html ），感觉挺有意思

**Comment by isnowfy** [comment]
早就有这个打算，做一个gitcafe版的simple，可是gitcafe迟迟不出api，等到gitcafe出了api就可以搞了
