### ISSUE TITLE
安卓手机浏览器下无法显示左侧导航栏。

### ISSUE THREAD

**Issue by tsai1993** [isnowfy/simple#20]
好像苹果没有这个问题。

**Comment by isnowfy** [comment]
目前设计的是手机都不显示左侧导航栏来着，看来响应式做的还不完善。。觉得左侧栏在手机上有点占位置，还在想有没有更好的布局，如果你有更好的设计欢迎pull request

**Comment by mzt999** [comment]
这样的话，左侧导航栏添加的page就无法显示了呢

**Comment by isnowfy** [comment]
@zombiephan 是有这样的问题，设计还需要完善
