### ISSUE TITLE
Italic markdown appears underlined

### ISSUE THREAD

**Issue by boissonnfive** [isnowfy/simple#22]
Hello,

great job !
as said in title, italic markdown words or sentences (like *Hello Wolrd!*) appears underlined in simple.

After investigation, it comes from your file entry.css :

    em{padding-bottom:.05em;font-style:inherit;font-weight:inherit;border-bottom:2px dotted #8b98a0}

should be replaced by :

    em{padding-bottom:.05em;font-style:italic;font-weight:inherit;/*border-bottom:2px dotted #8b98a0*/}

This is just my humble opinion. Feel free to use it and test it more deeply.

Have a nice day.
Bruno.

**Comment by isnowfy** [comment]
Thanks for your advice, the underlined was one of the decorates to em, if you dont like the underlined, you can fork the simple project, modify the file and then generate static blog with your own simple, thanks and enjoy it :)
