### ISSUE TITLE
每次发博客都需要在simple登陆发布吗？

### ISSUE THREAD

**Issue by Yuan-Hang** [isnowfy/simple#24]
请问有方法能直接在本地编辑好了push上去吗

**Comment by isnowfy** [comment]
simple就是方便那些不会git push的人用的，你也可以fork simple，然后就可以在你自己的位置登录编辑

**Comment by Yuan-Hang** [comment]
我现在修改了simple登陆地点，可是有没有在本地用markdown编辑然后push的办法0-0

**Comment by isnowfy** [comment]
没有呢，这种需求的话可以考虑用jekyll
