### ISSUE TITLE
"something error" when sign in.

### ISSUE THREAD

**Issue by hujy23** [isnowfy/simple#25]
![](http://ww2.sinaimg.cn/large/005JFI4ogw1f8jtto4kt7j30g00e875e.jpg)

**Comment by isnowfy** [comment]
密码没输错？

**Comment by hujy23** [comment]
确认没有输错，一两个星期前就不能登了，我刚刚把chrome在http://isnowfy.github.io/simple/和https://github.com/的密码记录都删了，然后在https://github.com/退出github账户，重新登了一下，账户密码没记错，然后再登simple还是登不上T_T输了很多遍都不行

**Comment by woooool** [comment]
@hujy23 是正常的呢

**Comment by isnowfy** [comment]
@hujy23 有点奇怪，话说你的帐户有没有经过email验证之类的

**Comment by hujy23** [comment]
@isnowfy @woooool  啊！登录成功了！刚刚仔细看那张截图，意识到右上角的“广告净化器”扩展，然后把simple加入白名单，登录就成功了。有一点变化是点登录会有一个小动画，然后成功登录。之前尝试登录很多次都是没有动画的，都是立即提示something error。看来是这个扩展导致的，非常感谢～(￣▽￣～)~

**Comment by isnowfy** [comment]
成功就好，难道被认为是广告了，好囧
