### ISSUE TITLE
hi，为啥不做comment功能啊

### ISSUE THREAD

**Issue by AlwaysLately** [isnowfy/simple#30]

**Comment by isnowfy** [comment]
因为这个是纯网页的，没有服务器，做不了comment，所以只能用第三方的

**Comment by Antecer** [comment]
其实可以做的，只要利用isue就行了。

2017-04-10 14:15 GMT+08:00 Rui Wang <notifications@github.com>:

**Comment by isnowfy** [comment]
@Antecer 是可以，但是考虑到如果用issue的话，就只能有github账户的人才能评论了，不是很通用

**Comment by Antecer** [comment]
要相信有总比没有好，哪怕它体验感受差点。

2017-04-10 19:55 GMT+08:00 Rui Wang <notifications@github.com>:

**Comment by isnowfy** [comment]
@Antecer 现在有可以用的评论系统，已经和disqus集成好了，在这边填个shortname就能行，比issue的体验好很多

**Comment by Antecer** [comment]
@isnowfy 秉承着完全寄生于git的理念，能不依赖第三方最好啦。

**Comment by AlwaysLately** [comment]
嗯嗯，能支持就显得更完善了

**Comment by tjy-cool** [comment]
@isnowfy你说的评论系统要怎么做呀，我好像没有看到呢

**Comment by isnowfy** [comment]
@tjy-cool 目前用的disqus的评论系统，代码里可以看到
