### ISSUE TITLE
我登陆http://isnowfy.github.io/simple/之后，修改好的模板全变了

### ISSUE THREAD

**Issue by tjy-cool** [isnowfy/simple#31]
我想问下如何可以使登陆http://isnowfy.github.io/simple/后，可以继续使用自己的模板，谢谢

**Comment by isnowfy** [comment]
fork这个项目之后，然后修改模板，后面就可以从你自己的xxx.github.io/simple之类的来登录使用你自己的simple了~

**Comment by tjy-cool** [comment]
已经搞好了，https://tjy-cool.github.io/，操作起来还是很简单的，感谢

**Comment by tjy-cool** [comment]
已经搞好了，https://tjy-cool.github.io，操作起来还是很简单的，感谢
