### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by zorro-long** [isnowfy/simple#6]
1. sign in on page http://isnowfy.github.io/simple/  
2. show error "something error" beside "Sign in" button  

PS: I think it should be some user validation issue on this. Maybe github account issue or simple project issue.

**Comment by kuiwang** [comment]
Why not add "two-factor authentication code"

**Comment by isnowfy** [comment]
@kuiwang While I use https://github.com/michael/github this repo to interact with github api, but it seems the repo only support the basic auth.
